version: '3.8'

services:
  db:
    container_name: postgres-cards
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - db:/data/postgres
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5430:5432"
    networks:
      - db



    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: